version: '3'

networks:
  NutriSave_network:
    driver: bridge  
    ipam:
      config:
        - subnet: 172.24.0.0/24
          gateway: 172.24.0.1

services:

#docker-compose -f docker-compose-NutriSave.yml up NutriSave_postgres_local
  NutriSave_postgres_local:
    container_name: postgres-NutriSave-local
    image: postgres:12.2-alpine
    ports:
      - 5234:5234
    networks:
      NutriSave_network:
        ipv4_address: 172.24.0.100
    environment:
      - POSTGRES_DB=NutriSave
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123@mudar

  #docker-compose -f docker-compose-NutriSave.yml up NutriSave_pgadmin
  NutriSave_pgadmin:
    image: dpage/pgadmin4
    container_name: NutriSave-pgadmin
    ports:
      - 15234:80
    networks:
      - NutriSave_network
    environment:
      - PGADMIN_DEFAULT_PASSWORD=p0stgr3s
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
    depends_on:
      - NutriSave_postgres_local